developmentBenchmark: developmentBenchmark.c
	gcc developmentBenchmark.c -o developmentBenchmark

all: countFivesInNElements.c countFivesInRandomNElements.c countFivesInSparseNElements.c findOneInNElements.c
	gcc countFivesInNElements.c -o countFivesInNElements
	gcc countFivesInRandomNElements.c -o countFivesInRandomNElements
	gcc countFivesInSparseNElements.c -o countFivesInSparseNElements
	gcc findOneInNElements.c -o findOneInNElements
